# https://taskfile.dev

version: "3"

vars:
  INSTAL_CONTAINER: instalcli/instal

tasks:
  default:
    deps: [ build, ght ]

  set-tag-and-date:
    cmds:
      - if [ -f "date.txt" ]; then rm date.txt; fi
      - if [ -f "tag.txt" ]; then rm tag.txt; fi
      - go run ./scripts/date.go >> date.txt
      - git describe --abbrev=0 --tags >> tag.txt

  build:
    cmds:
      - task: set-tag-and-date
      - go mod tidy
      - go build -ldflags "-X main.version=$(cat tag.txt) -X main.buildDate=$(cat date.txt)" -o instal

  install:
    deps: [ build ]
    cmds:
      - sudo mv instal /usr/local/bin

  remove:
    cmds:
      - sudo rm -rf /usr/local/bin/instal

  instal-container:
    deps: [ just-build-instal-container, build-instal-container, build-instal-container-with-cache ]

  just-build-instal-container:
    cmds:
      - docker build -t "{{ .INSTAL_CONTAINER }}" .

  build-instal-container:
    deps: [ just-build-instal-container ]
    cmds:
      - docker push "{{ .INSTAL_CONTAINER }}"

  build-instal-container-with-cache:
    cmds:
      - docker pull "{{ .INSTAL_CONTAINER }}":latest
      - docker build -t "{{ .INSTAL_CONTAINER }}" --cache-from "{{ .INSTAL_CONTAINER }}":latest .
      - docker push "{{ .INSTAL_CONTAINER }}"

  check_node_moduels:
    dir: ./scripts/gh-instal
    cmds:
      - if ! [ -d "node_modules" ]; then yarn; fi

  ght:
    deps: [ build ]
    cmds:
      - task: check_node_moduels
      - node ./scripts/gh-instal/gh-ins.js
